name: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"
description: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"

inputs:
  dependency-graph:
    description: 'Possible values: generate, generate-and-submit and download-and-submit. Default value is disabled. Only applicable to main branch'
    required: false
    default: disabled

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      id: setup-java
      with:
        distribution: 'temurin'
        java-version: '19'
    - uses: gradle/actions/wrapper-validation@v3
    - name: Setup Gradle
      if: github.ref_name != 'main'
      uses: gradle/actions/setup-gradle@v3
    - name: Setup Gradle with dependency generation
      if: github.ref_name == 'main'
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ inputs.github_token }}
      uses: gradle/actions/setup-gradle@v3
      with:
        dependency-graph: ${{ inputs.dependency-graph }}
