name: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"
description: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"

inputs:
  dependency-graph:
    description: "Possible values: generate, generate-and-submit and download-and-submit. Default value is disabled. Only applicable to main branch"
    required: false
    default: disabled
  java-version:
    description: "The version of jave to be used in setup-java"
    required: false
    default: "19"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v5
      id: setup-java
      with:
        distribution: "temurin"
        java-version: ${{inputs.java-version}}
    - uses: gradle/actions/wrapper-validation@v4
    - name: Setup Gradle
      if: github.ref_name != 'main'
      uses: gradle/actions/setup-gradle@v4
    - name: Setup Gradle with dependency generation
      if: github.ref_name == 'main'
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ inputs.github_token }}
      uses: gradle/actions/setup-gradle@v4
      with:
        dependency-graph: ${{ inputs.dependency-graph }}
