name: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"
description: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      id: setup-java
      with:
        distribution: 'temurin'
        java-version: '19'
    - uses: gradle/wrapper-validation-action@v1.1.0
      id: gradle-wrapper-validation
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
