name: "Upload files to NAV CDN"
description: "Validates inputs and uploads a folder to NAV CDN using Workload Identity"

inputs:
  team:
    required: true
    type: string
  source:
    required: true
    type: string
  destination:
    required: true
    type: string
  nais-management-project-id:
    required: true
    type: string
  nais-workload-identity-provider:
    required: true
    type: string
  skip-if-source-missing:
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.team }}" ]]; then
          echo "Input 'team' must be set"
          exit 1
        fi

        if [[ -z "${{ inputs.source }}" ]]; then
          echo "Input 'source' must be set"
          exit 1
        fi

        if [[ -z "${{ inputs.destination }}" ]]; then
          echo "Input 'destination' must be set"
          exit 1
        fi

        if [[ -z "${{ inputs.nais-management-project-id }}" ]]; then
          echo "Input 'nais-management-project-id' must be set"
          exit 1
        fi

        if [[ -z "${{ inputs.nais-workload-identity-provider }}" ]]; then
          echo "Input 'nais-workload-identity-provider' must be set"
          exit 1
        fi

        if [[ ! -d "${{ inputs.source }}" ]]; then
          if [[ "${{ inputs.skip-if-source-missing }}" == "true" ]]; then
            echo "Source folder '${{ inputs.source }}' not found; skipping CDN upload."
            echo "SKIP_CDN_UPLOAD=true" >> "$GITHUB_ENV"
            exit 0
          fi

          echo "Source folder '${{ inputs.source }}' not found."
          exit 1
        fi

    - name: Upload files to NAV CDN
      if: ${{ env.SKIP_CDN_UPLOAD != 'true' && github.actor != 'dependabot[bot]' }}
      uses: nais/deploy/actions/cdn-upload/v2@master
      with:
        team: ${{ inputs.team }}
        source: ${{ inputs.source }}
        destination: ${{ inputs.destination }}
        project_id: ${{ inputs.nais-management-project-id }}
        identity_provider: ${{ inputs.nais-workload-identity-provider }}
