name: "Builds a bootjar, creates a docker image and uploads it to GAR"
description: "Builds a bootjar, creates a docker image and uploads it to GAR"

inputs:
  app:
    required: true
    type: string
  github_token:
    required: true
    type: string
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: navikt/teamesyfo-github-actions-workflows/actions/gradle-cached@main
      with:
        dependency-graph: generate-and-submit
    - name: Build bootJar
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ inputs.github_token }}
      shell: bash
      run: |
        ./gradlew bootJar -x test
    - name: Push docker image to GAR
      uses: nais/docker-build-push@v0
      env:
        TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
      if: ${{ github.actor != 'dependabot[bot]' }}
      id: docker-build-push
      with:
        team: team-esyfo
