name: Merge dependabot pr

on:
  workflow_call:

concurrency:
  group: merge-dependabot-automerge
  cancel-in-progress: false

jobs:
  merge-pullrequests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Automerge dependabot PRs
        uses: actions/github-script@v7
        with:
          script: |
            const run = require('./.github/scripts/merge-dependabot.js')
            await run({ github, context, core })
