on:
  workflow_call:
jobs:
  deploy-dev:
    if: github.ref_name != 'main' && github.event.pull_request.draft == false
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy redis to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: dev-gcp
          TEAM: team-esyfo
          RESOURCE: redis.yaml
          PRINT_PAYLOAD: true
  deploy-prod:
    if: github.ref_name == 'main'
    name: Deploy redis to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy to redis dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: prod-gcp
          TEAM: team-esyfo
          RESOURCE: redis.yaml
          PRINT_PAYLOAD: true
