name: "Build and deploy"

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      id:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: "18"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      cdn_url: ${{ steps.extract-manifest-url.outputs.url }}
      image: ${{ steps.docker-build-push.outputs.image }}

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com
          cache: npm
      - name: Install dependencies
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cypress tests
        run: npx cypress run --component
      - name: Build application
        run: npm run build

      - name: cdn-upload
        id: cdn-upload
        uses: nais/deploy/actions/cdn-upload/v2@fa754451577294aae42872a69b888b3470478ec1 # v2
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
        with:
          team: team-esyfo
          source: ./dist/
          destination: ${{ inputs.app }}

      - name: Extract manifest url
        id: extract-manifest-url
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
        run: |
          files="${{ steps.cdn-upload.outputs.uploaded }}"
          first_file=$(echo $files | cut -d',' -f1)
          echo "url=https://cdn.nav.no/$first_file" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
        uses: nais/docker-build-push@ae613eff6f44f0323476eda1c3994a7c518761c3 # v0
        id: docker-build-push
        with:
          team: team-esyfo

  update-manifest-dev:
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    needs: build
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@67dc876fb9e1a0b115e47a36fd46a1c7b0064d4c # main
    with:
      cluster: dev-gcp
      id: ${{ inputs.id }}
      url: ${{needs.build.outputs.cdn_url}}
    secrets: inherit

  update-manifest-prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@67dc876fb9e1a0b115e47a36fd46a1c7b0064d4c # main
    with:
      cluster: prod-gcp
      id: ${{ inputs.id }}
      url: ${{needs.build.outputs.cdn_url}}
    secrets: inherit
