name: "Installs node, installs npm dependencies with cache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  app:
    required: true
    description: "Application name"
  env:
    required: true
    description: "Environment name"
  NPM_AUTH_TOKEN:
    required: true
    description: "NPM authentication token"
  node-version:
    required: false
    description: "Node version"
  server-actions-encryption-key:
    description: "Encryption key for Next.js Server Actions, should be a 32-byte base64 string"
    required: false

outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: navikt/teamesyfo-github-actions-workflows/actions/npm-cached@main
      with:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
        node-version: ${{ inputs.node-version }}
    - name: Copy appropriate env file to root
      shell: bash
      run: |
        echo "Copying nais/envs/.env.${{ inputs.env }}..."
        cp nais/envs/.env.${{ inputs.env }} .env.production
    - id: npm-build
      shell: bash
      run: |
        if [ -n "${{ inputs.server-actions-encryption-key }}" ]; then
          export NEXT_SERVER_ACTIONS_ENCRYPTION_KEY="${{ inputs.server-actions-encryption-key }}"
          echo "NEXT_SERVER_ACTIONS_ENCRYPTION_KEY is set, opting in with custom key."
        else
          echo "NEXT_SERVER_ACTIONS_ENCRYPTION_KEY is not set, building with default behavior."
          unset NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
        fi
        
        npm run build
      env:
        NEXT_PUBLIC_VERSION: ${{ github.sha }}
    - name: Upload static files to NAV CDN
      uses: nais/deploy/actions/cdn-upload/v2@fa754451577294aae42872a69b888b3470478ec1 # v2
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        team: team-esyfo
        source: ./.next/static
        destination: "/${{ inputs.app }}/_next"
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
    - name: Push docker image to GAR
      uses: nais/docker-build-push@v0
      if: ${{ github.actor != 'dependabot[bot]' }}
      id: docker-build-push
      with:
        team: team-esyfo
        image_suffix: ${{ inputs.env }}
